# Generated by Django 2.2.10 on 2020-02-15 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chomik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producent', models.CharField(max_length=64)),
                ('waga', models.PositiveIntegerField()),
                ('ekran', models.CharField(max_length=64)),
                ('usb_count', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pecet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producent', models.CharField(max_length=64)),
                ('waga', models.PositiveIntegerField()),
                ('zasilacz', models.CharField(max_length=64)),
                ('karta_graficzna', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='reserwacja',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to='chomik.Sala'),
        ),
    ]
