# Generated by Django 2.2.10 on 2020-02-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chomik', '0002_auto_20200215_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='sn',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pecet',
            name='sn',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
