# Generated by Django 2.2.10 on 2020-02-15 14:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chomik', '0003_auto_20200215_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChomikDżejson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
